[Service]
HTTPListenAddr = "localhost:3000"
RPCConcurrency = 10
RPCTimeout = "10s"

[Account]
Mode = "keystore"
KeystorePath = "./keystore"
Password = "sentry"
Address = "0x837060bd423eFcDd5B7b6B92aB3CFc74B9CD0df4"

[[Validators]]
PrivateURL = "http://127.0.0.1:8546"
PublicHostName = "127.0.0.1"

[[Builders]]
Address = "0x295e26495CEF6F69dFA69911d9D8e4F3bBadB89B"
URL = "http://localhost:8555"

[FullNode]
URL = "http://localhost:8545"

[Debug]
ListenAddr = "localhost:8090"

[Log]
RootDir = "./logs"
Level = "debug"