[Service]
HTTPListenAddr = "localhost:8555" # The address to listen on for HTTP requests.
RPCConcurrency = 100 # The maximum number of concurrent requests.
RPCTimeout = "10s" # The timeout for RPC requests.

[[Validators]]
PrivateURL = "http://10.200.31.36:8545"
PublicHostName = "bsc-testnet-elbrus.bnbchain.org"
PayAccountMode = "privateKey"
PrivateKey = "b1fed931ad503ba9d029e86c2bd957cccbeb54f5995441f34796ddbee68a53cf"

[[Validators]]
PrivateURL = "http://10.200.33.92:8545"
PublicHostName = "bsc-testnet-ararat.bnbchain.org"
PayAccountMode = "privateKey"
PrivateKey = "ce3f1b7573842f80764ec12573a049612bc49c8f940c00fb71d755f66f647503"

[[Builders]]
Address = "0x980A75eCd1309eA12fa2ED87A8744fBfc9b863D5" # The address of the builder.
URL = "http://bsc-builder-1" # The public URL of the builder.

[[Builders]]
Address = "0x980A75eCd1309eA12fa2ED87A8744fBfc9b863D5"
URL = "http://bsc-builder-2"